# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Deployment Process
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: "/nextjs-ecommerce"
    steps:
      - name: Start CI
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build App
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: Export Deployment Files
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: export
        run: sudo touch ./out/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
